---
- hosts: master
  remote_user: root
  tasks:
  - name: setup code on master
    copy:
     src: "/tmp/apache-deployment.yml"
     dest: "/tmp/apache-deployment.yml"
     mode: 0755

  - name: Create a Deployment and service
    shell: 'kubectl apply -f /tmp/apache-deployment.yml ; kubectl get service'
    register: myoutput

  - name: print output
    debug:
      msg: "{{ myoutput.stdout }}"
